name: Cargo bump

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test cargo-bump
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run cargo-bump
        id: cargo-bump
        uses: ./
        with:
          working-directory: .
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          base: "master"
          labels: "merge when passing"
          title: "${{ github.repository }}: Update ${{ steps.cargo-bump.outputs.package_name }} to ${{ steps.cargo-bump.outputs.new_version }}"
          branch: "deps/upgraded-to-${{ steps.cargo-bump.outputs.new_version }}"
          body: "View [CHANGES](https://github.com/${{ github.repository }}/compare/${{ steps.cargo-bump.outputs.old_version }}...${{ steps.cargo-bump.outputs.new_version }})"
          token: ${{ secrets.PAT_TOKEN }}
